[package]
name = "vm"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "chroma-vm"
path = "src/main.rs"

[dependencies]
shared = { path = "../shared" }
clap.workspace = true
macroquad.workspace = true
fastrand.workspace = true